service: sls-ts-test
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DB_CONNECTION: ${env:DB_CONNECTION}
    DB_HOST: ${env:DB_HOST}

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  esbuild:
    config: './config.js'
